<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"ru\">\n";
echo "  <head>\n";
echo "    <meta charset=\"UTF-8\" />\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n";
echo "    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n";
echo "    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\n";
echo "    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\n";
echo "    <link\n";
echo "      href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Ubuntu:wght@400;700&display=swap\"\n";
echo "      rel=\"stylesheet\"\n";
echo "    />\n";
echo "    <link rel=\"stylesheet\" href=\"./css/style.css\" />\n";
echo "    <link rel=\"stylesheet\" href=\"./css/media.css\" />\n";
echo "    <script src=\"./js/modal.js\" defer=\"defer\"></script>\n";
echo "    <script src=\"./js/scroll.js\" defer=\"defer\"></script>\n";
echo "    <script src=\"./js/lists.js\" defer=\"defer\"></script>\n";
echo "    <title>Берегиня</title>\n";
echo "  </head>\n";
echo "  <body>\n";
echo "    <header class=\"header\">\n";
echo "      <div class=\"container\">\n";
echo "        <div class=\"block__header\">\n";
echo "          <div class=\"block__adress\">\n";
echo "            <p class=\"adress\">\n";
echo "              Адрес завода: 140127, Московская область, Раменский р-н, пос.\n";
echo "              санатория «Раменское»\n";
echo "            </p>\n";
echo "          </div>\n";
echo "          <div class=\"block__contact\">\n";
echo "            <div class=\"span__block\">\n";
echo "              <img src=\"./img/icon/whatsapp1.svg\" alt=\"img\" class=\"what\" />\n";
echo "              <p class=\"numb\">8 (903) 578-85-77</p>\n";
echo "            </div>\n";
echo "            <div class=\"span__block_teleg\">\n";
echo "              <img src=\"./img/icon/telegram2.svg\" alt=\"img\" class=\"what\" />\n";
echo "              <p class=\"adress__teleg\">@bereginya.ru</p>\n";
echo "            </div>\n";
echo "            <div class=\"span__block_not\">\n";
echo "              <img src=\"./img/icon/interface.svg\" alt=\"img\" class=\"what\" />\n";
echo "              <a class=\"adress__email\">info@bereginya.ru — написать письмо</a>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </header>\n";
echo "\n";
echo "    <main>\n";
echo "      <section class=\"promo\">\n";
echo "        <div class=\"container\">\n";
echo "          <div class=\"modal__bg_email\">\n";
echo "            <div class=\"wrapp__email\">\n";
echo "              <div class=\"modal__email\">\n";
echo "                <h3 class=\"tile__modal_email\">Мы вам напишем</h3>\n";
echo "                <p class=\"text_mod_email\">\n";
echo "                  Оставьте ваши данные и мы свяжемся с вами. Мы не занимаемся\n";
echo "                  рассылкой рекламных сообщений, а так же<br />не передаем\n";
echo "                  контактные данные третьим лицам\n";
echo "                </p>\n";
echo "                <a href=\"#\" class=\"close_email_mod\"></a>\n";
echo "                <div class=\"input_name_block\">\n";
echo "                  <input\n";
echo "                    type=\"text\"\n";
echo "                    class=\"modal_email_un\"\n";
echo "                    placeholder=\"Ваше имя\"\n";
echo "                  />\n";
echo "                  <input\n";
echo "                    type=\"text\"\n";
echo "                    class=\"modal_email_un\"\n";
echo "                    placeholder=\"Ваша e-mail\"\n";
echo "                  />\n";
echo "                  <input\n";
echo "                    type=\"text\"\n";
echo "                    class=\"modal_email_un\"\n";
echo "                    placeholder=\"Ваш телефон\"\n";
echo "                  />\n";
echo "                </div>\n";
echo "                <!-- /.input_name_block -->\n";
echo "                <div class=\"massenge\">\n";
echo "                  <input\n";
echo "                    type=\"text\"\n";
echo "                    class=\"mes_input\"\n";
echo "                    placeholder=\"Опишите свою проблему ...\"\n";
echo "                  />\n";
echo "                </div>\n";
echo "                <!-- /.massenge -->\n";
echo "                <div class=\"btn__ckeckid\">\n";
echo "                  <a href=\"\" class=\"btn_panel_bran\">Перезвоните мне</a>\n";
echo "                  <div class=\"check_box\">\n";
echo "                    <label class=\"label\"\n";
echo "                      ><input type=\"checkbox\" class=\"checkbox\" />\n";
echo "                      <span class=\"fake\"></span>\n";
echo "                      <span class=\"text_chek_panel\"\n";
echo "                        ><span class=\"text__check\">Согласие на обработку </span\n";
echo "                        ><span class=\"text__check_sub\"\n";
echo "                          >персональных данных</span\n";
echo "                        ></span\n";
echo "                      ></label\n";
echo "                    >\n";
echo "                  </div>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"block__promo\">\n";
echo "            <div class=\"block__logo\">\n";
echo "              <div class=\"burger__menu\"><a href=\"#\" class=\"buger\"></a></div>\n";
echo "              <a href=\"#\" class=\"logo__ind\"><div class=\"logo\"></div></a>\n";
echo "            </div>\n";
echo "            <div class=\"block__link\">\n";
echo "              <a href=\"#\" class=\"link\">История компании </a\n";
echo "              ><a href=\"#\" class=\"link\">Доставка </a\n";
echo "              ><a href=\"#\" class=\"link__not\">Контакты</a>\n";
echo "            </div>\n";
echo "            <div class=\"block__phone\">\n";
echo "              <a href=\"#\" class=\"search\"></a>\n";
echo "              <input\n";
echo "                type=\"text\"\n";
echo "                class=\"search__active\"\n";
echo "                placeholder=\"Найдётся всё...\"\n";
echo "              />\n";
echo "              <div class=\"call\">\n";
echo "                <img\n";
echo "                  src=\"./img/icon/interface2.svg\"\n";
echo "                  alt=\"img\"\n";
echo "                  class=\"call__icon\"\n";
echo "                />\n";
echo "                <a class=\"numb__call\">8 (903) 578-85-77</a>\n";
echo "                <a href=\"#\" class=\"requestcall\">заказать звонок</a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"block__promo__info\">\n";
echo "            <!-- главный блок -->\n";
echo "            <div class=\"line\">\n";
echo "              <!-- этот див сделал для отделения текста от бутылок -->\n";
echo "              <div class=\"icon__time\">\n";
echo "                <!--подблок (колонка) -->\n";
echo "                <h2 class=\"title__time\">\n";
echo "                  Берегиня — это<br /> здоровье, энергия<br />и вдохновение\n";
echo "                </h2>\n";
echo "                <!--контентная часть (сверху и с низу)-->\n";
echo "                <div class=\"icons\">\n";
echo "                  <img\n";
echo "                    src=\"./img/icon/wall-clock1.svg\"\n";
echo "                    alt=\"icon\"\n";
echo "                    class=\"time\"\n";
echo "                  />\n";
echo "                  <p class=\"time__text\">Для бодрого пробуждения</p>\n";
echo "                </div>\n";
echo "                <div class=\"icons_dish\">\n";
echo "                  <img\n";
echo "                    src=\"./img/icon/wall-clock1.svg\"\n";
echo "                    alt=\"icon\"\n";
echo "                    class=\"time\"\n";
echo "                  />\n";
echo "                  <p class=\"time__text\">Во время тренировки</p>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "              <div class=\"block__eat\">\n";
echo "                <!--подблок (колонка)-->\n";
echo "                <p class=\"text__eat\">\n";
echo "                  Благодаря вулканическим минералам жизнь бьет <br />ключом.\n";
echo "                  Неважно – офлайн или онлайн. В ритме города <br />или стихии.\n";
echo "                  Дома, на море, на газоне, под колонкой, на<br />балконе.\n";
echo "                  Неважно, в 30 или в 130! Когда ты полон<br />здоровья, истории\n";
echo "                  начинаются снова и снова\n";
echo "                </p>\n";
echo "                <div class=\"icon_eat\">\n";
echo "                  <img src=\"./img/icon/eat.svg\" alt=\"eat\" class=\"time\" />\n";
echo "                  <p class=\"time__text\">Вместо вредного перекуса</p>\n";
echo "                </div>\n";
echo "                <div class=\"icons_car\">\n";
echo "                  <img src=\"./img/icon/car.svg\" alt=\"icon\" class=\"time\" />\n";
echo "                  <p class=\"time__text\">В дороге</p>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <!-- главный блок конец -->\n";
echo "            <div class=\"bottle\">\n";
echo "              <!-- главный бутылочный блок -->\n";
echo "              <img src=\"./img/Бутылки.png\" alt=\"\" class=\"bottle__img\" />\n";
echo "            </div>\n";
echo "            <div class=\"round\"><a href=\"#\" class=\"down\"></a></div>\n";
echo "            <div class=\"window_close\">\n";
echo "              <div class=\"drop__wrapp\">\n";
echo "                <div class=\"drop_close\">\n";
echo "                  <a href=\"#\" class=\"close__burger\"></a>\n";
echo "                  <div class=\"dropdown_box\">\n";
echo "                    <div class=\"box__link\">\n";
echo "                      <a href=\"./branding.html\" class=\"link__page\"\n";
echo "                        >Брендирование воды</a\n";
echo "                      >\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                  <div class=\"dropdown_box\">\n";
echo "                    <div class=\"box__link\">\n";
echo "                      <a href=\"./spill.html\" class=\"link__page_cont\"\n";
echo "                        >Контрактный розлив</a\n";
echo "                      >\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                  <div class=\"dropdown_box\">\n";
echo "                    <div class=\"box__link\">\n";
echo "                      <a href=\"./line.html\" class=\"link__page_pump\"\n";
echo "                        >Вода на розлив</a\n";
echo "                      >\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                  <div class=\"dropdown_box\">\n";
echo "                    <div class=\"box__link\">\n";
echo "                      <a href=\"./catalog.html\" class=\"link__page\"\n";
echo "                        >Напитки оптом</a\n";
echo "                      >\n";
echo "                      <span class=\"gren_round\">%</span>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                  <div class=\"dropdown_box\">\n";
echo "                    <div class=\"box__link\">\n";
echo "                      <a href=\"./catalog.html\" class=\"link__page\">Вода оптом</a>\n";
echo "                      <span class=\"gren_round_two\">%</span>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                  <div class=\"dropdown_box\">\n";
echo "                    <div class=\"box__link\">\n";
echo "                      <a href=\"./production.html\" class=\"link__page_plast\"\n";
echo "                        >Изготовление ПЭТ тары</a\n";
echo "                      >\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                  <div class=\"dropdown_box\">\n";
echo "                    <div class=\"box__link\">\n";
echo "                      <a href=\"#\" class=\"link__page_wat\">Бренды</a>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"wrapp_window\">\n";
echo "            <div class=\"modal_window\">\n";
echo "              <div class=\"wind\">\n";
echo "                <div class=\"close__modal\">\n";
echo "                  <h3 class=\"title__wind\">Мы вам перезвоним</h3>\n";
echo "                  <a href=\"#\" class=\"close_btn\"></a>\n";
echo "                </div>\n";
echo "                <p class=\"text__wind\">\n";
echo "                  Оставьте ваши данные и мы свяжемся с вами. Мы не занимаемся\n";
echo "                  рассылкой рекламных сообщений, а так же не<br />передаем\n";
echo "                  контактные данные третьим лицам\n";
echo "                </p>\n";
echo "                <form action=\"#\" class=\"form_bran_modal\">\n";
echo "                  <div class=\"cont_input\">\n";
echo "                    <input\n";
echo "                      type=\"text\"\n";
echo "                      class=\"panel_bran\"\n";
echo "                      placeholder=\"Ваше имя\"\n";
echo "                    />\n";
echo "                    <input\n";
echo "                      type=\"text\"\n";
echo "                      class=\"panel_bran\"\n";
echo "                      placeholder=\"Ваш телефон\"\n";
echo "                    />\n";
echo "                  </div>\n";
echo "                  <!-- /.cont_input -->\n";
echo "                  <div class=\"btn__ckeckid\">\n";
echo "                    <a href=\"#\" class=\"btn_panel_bran\">Перезвоните мне</a>\n";
echo "                    <div class=\"check_box\">\n";
echo "                      <label class=\"label\"\n";
echo "                        ><input type=\"checkbox\" class=\"checkbox\" />\n";
echo "                        <span class=\"fake\"></span>\n";
echo "                        <span class=\"text_chek_panel\"\n";
echo "                          ><span class=\"text__check\"\n";
echo "                            >Согласие на обработку </span\n";
echo "                          ><span class=\"text__check_sub\"\n";
echo "                            >персональных данных</span\n";
echo "                          ></span\n";
echo "                        ></label\n";
echo "                      >\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                </form>\n";
echo "                <!-- /.form_bran_panel -->\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </section>\n";
echo "\n";
echo "      <section class=\"plan__products\">\n";
echo "        <div class=\"container\">\n";
echo "          <div class=\"text__plant\">\n";
echo "            <h2 class=\"title__plant\">Продукция завода</h2>\n";
echo "            <p class=\"text_section\">\n";
echo "              Существует три основных вида природных питьевых вод: лечебные,\n";
echo "              лечебно-столовые и столовые (питьевые).<br />Лечебные воды\n";
echo "              обладают выраженным лечебным действием на организм человека и\n";
echo "              используются<br />исключительно в медицинских целях.\n";
echo "              Лечебно-столовые воды применяются как лечебное и\n";
echo "              профилактическое<br />средство при конкретных заболеваниях.\n";
echo "            </p>\n";
echo "          </div>\n";
echo "          <div class=\"card__plant\">\n";
echo "            <div class=\"sup__card\">\n";
echo "              <div class=\"card__product\">\n";
echo "                <div class=\"circle\">\n";
echo "                  <img src=\"./img/Component3.png\" alt=\"img\" class=\"bereg\" />\n";
echo "                </div>\n";
echo "                <a href=\"#\" class=\"btn__product\">Питьевая вода</a>\n";
echo "              </div>\n";
echo "              <div class=\"card__product\">\n";
echo "                <div class=\"circle\">\n";
echo "                  <img src=\"./img/Component3.png\" alt=\"img\" class=\"bereg\" />\n";
echo "                </div>\n";
echo "                <a href=\"#\" class=\"btn__product\">Берегиня-1</a>\n";
echo "              </div>\n";
echo "              <div class=\"card__product\">\n";
echo "                <div class=\"circle\">\n";
echo "                  <img src=\"./img/Component1.png\" alt=\"img\" class=\"drink\" />\n";
echo "                </div>\n";
echo "                <a href=\"#\" class=\"btn__product\">Газированные напитки</a>\n";
echo "              </div>\n";
echo "              <div class=\"card__product\">\n";
echo "                <div class=\"circle\">\n";
echo "                  <img src=\"./img/Component2.png\" alt=\"img\" class=\"bott\" />\n";
echo "                </div>\n";
echo "                <a href=\"#\" class=\"btn__product padd\"\n";
echo "                  >Ассортимент<br />питьевых вод</a\n";
echo "                >\n";
echo "              </div>\n";
echo "              <div class=\"card__product\">\n";
echo "                <div class=\"circle\">\n";
echo "                  <img src=\"./img/Component1.png\" alt=\"img\" class=\"drink\" />\n";
echo "                </div>\n";
echo "                <a href=\"#\" class=\"btn__product\">Газированные напитки</a>\n";
echo "              </div>\n";
echo "              <div class=\"card__product_card_sett\">\n";
echo "                <div class=\"circle\">\n";
echo "                  <img src=\"./img/Component2.png\" alt=\"img\" class=\"bott\" />\n";
echo "                </div>\n";
echo "                <a href=\"#\" class=\"btn__product padd\"\n";
echo "                  >Ассортимент<br />питьевых вод</a\n";
echo "                >\n";
echo "              </div>\n";
echo "              <div class=\"card__product\">\n";
echo "                <div class=\"circle\">\n";
echo "                  <img src=\"./img/Component3.png\" alt=\"img\" class=\"bereg\" />\n";
echo "                </div>\n";
echo "                <a href=\"#\" class=\"btn__product\">Питьевая вода</a>\n";
echo "              </div>\n";
echo "              <div class=\"card__product\">\n";
echo "                <div class=\"circle\">\n";
echo "                  <img src=\"./img/Component3.png\" alt=\"img\" class=\"bereg\" />\n";
echo "                </div>\n";
echo "                <a href=\"#\" class=\"btn__product\">Берегиня-1</a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <div class=\"sub__card\">\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"benefits\">\n";
echo "            <h2 class=\"title__benifits\">Преимущества воды “Берегиня”</h2>\n";
echo "            <div class=\"panel\">\n";
echo "              <div class=\"block__left\">\n";
echo "                <div class=\"panel__icons\">\n";
echo "                  <img\n";
echo "                    src=\"./img/icon/mountains1.svg\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"panel__img\"\n";
echo "                  />\n";
echo "                  <p class=\"text__panel box_text_panel\">Настоящая <br />горная вода</p>\n";
echo "                </div>\n";
echo "                <!-- /.panel__icons -->\n";
echo "                <div class=\"panel__icons sett__icon\">\n";
echo "                  <img\n";
echo "                    src=\"./img/icon/water-cycle1.svg\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"panel__img\"\n";
echo "                  />\n";
echo "                  <p class=\"text__panel\">Идеально<br />сбалансировання</p>\n";
echo "                </div>\n";
echo "                <!-- /.panel__icons -->\n";
echo "              </div>\n";
echo "              <!-- /.block__left -->\n";
echo "              <div class=\"block__img_panel\">\n";
echo "                <img\n";
echo "                  src=\"./img/stakan_na_glavnoy1.png\"\n";
echo "                  alt=\"img\"\n";
echo "                  class=\"glass\"\n";
echo "                />\n";
echo "              </div>\n";
echo "              <!-- /.block__img_panel -->\n";
echo "              <div class=\"block__right_panel\">\n";
echo "                <div class=\"panel__icons\">\n";
echo "                  <img\n";
echo "                    src=\"./img/icon/waterproof-fabric1.svg\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"panel__img\"\n";
echo "                  />\n";
echo "                  <p class=\"text__panel text__sett\">\n";
echo "                    Натуральный <br />природний состав\n";
echo "                  </p>\n";
echo "                </div>\n";
echo "                <!-- /.panel__icons -->\n";
echo "                <div class=\"panel__icons sett__icon\">\n";
echo "                  <img\n";
echo "                    src=\"./img/icon/leaf1.svg\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"panel__img\"\n";
echo "                  />\n";
echo "                  <p class=\"text__panel\">Идеально<br />сбалансировання</p>\n";
echo "                </div>\n";
echo "                <!-- /.panel__icons -->\n";
echo "              </div>\n";
echo "              <!-- /.block__right_panel -->\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <!-- /.benefits -->\n";
echo "        </div>\n";
echo "      </section>\n";
echo "      <!-- /.plan__products -->\n";
echo "\n";
echo "      <section class=\"catalog\">\n";
echo "        <div class=\"container\">\n";
echo "          <h2 class=\"title__catalog\">Каталог</h2>\n";
echo "          <div class=\"filter\">\n";
echo "            <div class=\"btn__filter\">\n";
echo "              <a href=\"#\" class=\"btn__sorting\">Объем</a>\n";
echo "              <div class=\"wrapp_vol_List\">\n";
echo "                <div class=\"volume__list\">\n";
echo "                  <div class=\"type__btn_vol\">\n";
echo "                    <a href=\"#\" class=\"btn_vol\">Объем</a>\n";
echo "                  </div>\n";
echo "                  <div class=\"type__list_volume_big\">\n";
echo "                    <p class=\"text_list_vol\">19 литров</p>\n";
echo "                  </div>\n";
echo "                  <div class=\"type__list_volume\">\n";
echo "                    <p class=\"text_list_vol\">5 литров</p>\n";
echo "                  </div>\n";
echo "                  <div class=\"type__list_volume\">\n";
echo "                    <p class=\"text_list_vol\">5 литров</p>\n";
echo "                  </div>\n";
echo "                  <div class=\"type__list_volume\">\n";
echo "                    <p class=\"text_list_vol\">5 литров</p>\n";
echo "                  </div>\n";
echo "                  <div class=\"type__list_volume\">\n";
echo "                    <p class=\"text_list_vol\">5 литров</p>\n";
echo "                  </div>\n";
echo "                  <div class=\"type__list_volume\">\n";
echo "                    <p class=\"text_list_vol\">5 литров</p>\n";
echo "                  </div>\n";
echo "                  <div class=\"type__list_volume\">\n";
echo "                    <p class=\"text_list_vol\">5 литров</p>\n";
echo "                  </div>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "              <a href=\"#\" class=\"btn__sorting_center sett__typ\">Тип </a\n";
echo "              ><a href=\"#\" class=\"btn__sorting_center sett_category\">Категория </a\n";
echo "              ><a href=\"#\" class=\"btn__sorting_center sett_touch\">Назначение </a\n";
echo "              ><a href=\"#\" class=\"btn__sorting_center sett_sorting\">Бренд </a\n";
echo "              ><a href=\"#\" class=\"btn__sorting_right\">Сортировка</a>\n";
echo "              <div class=\"wrapp_sor_List\">\n";
echo "                <div class=\"sortin__list\">\n";
echo "                  <div class=\"type__btn_sort\">\n";
echo "                    <a href=\"#\" class=\"btn_sor\">Сортировка</a>\n";
echo "                  </div>\n";
echo "                  <div class=\"type__list_sort_big\">\n";
echo "                    <p class=\"text_list_sort\">по возрастанию цены</p>\n";
echo "                  </div>\n";
echo "                  <div class=\"type__list_sort\">\n";
echo "                    <p class=\"text_list_sort\">по возрастанию цены</p>\n";
echo "                  </div>\n";
echo "                  <div class=\"type__list_sort\">\n";
echo "                    <p class=\"text_list_sort\">по возрастанию цены</p>\n";
echo "                  </div>\n";
echo "                  <div class=\"type__list_sort\">\n";
echo "                    <p class=\"text_list_sort\">по возрастанию цены</p>\n";
echo "                  </div>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <!-- /.filter -->\n";
echo "          <div class=\"card__catalog\">\n";
echo "            <div class=\"strip_sup\">\n";
echo "              <div class=\"card__botlle\">\n";
echo "                <div class=\"sup__info__card\">\n";
echo "                  <p class=\"round__hot\"></p>\n";
echo "                  <p class=\"round_percent\">%</p>\n";
echo "                  <img\n";
echo "                    src=\"./img/card__catalog.png\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"card_botlle\"\n";
echo "                  />\n";
echo "                  <p class=\"text__catalog__card\">\n";
echo "                    EsonStyle (ЕсонСтайл) - фитнес<br />резинки\n";
echo "                  </p>\n";
echo "                  <p class=\"grey__text__catalog\">\n";
echo "                    Природная питьевая вода высшего<br />качества,\n";
echo "                    озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                  </p>\n";
echo "                </div>\n";
echo "                <!-- /.sup__info__card -->\n";
echo "                <div class=\"sub__info__card\">\n";
echo "                  <div class=\"money\">\n";
echo "                    <span class=\"money__discount\">220 ₽ </span\n";
echo "                    ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                  </div>\n";
echo "                  <!-- /.money -->\n";
echo "                  <div class=\"btn__money\">\n";
echo "                    <p class=\"plus\">+</p>\n";
echo "                    <p class=\"minus\">-</p>\n";
echo "                    <p class=\"counter\">0</p>\n";
echo "                    <a href=\"#\" class=\"btn__cart\"></a>\n";
echo "                  </div>\n";
echo "                  <!-- /.btn__money -->\n";
echo "                </div>\n";
echo "                <!-- /.sub__info__card -->\n";
echo "              </div>\n";
echo "              <!-- /.card__botlle -->\n";
echo "              <div class=\"card__botlle\">\n";
echo "                <div class=\"sup__info__card\">\n";
echo "                  <p class=\"round__hot\"></p>\n";
echo "                  <p class=\"round_percent\">%</p>\n";
echo "                  <img\n";
echo "                    src=\"./img/card__catalog.png\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"card_botlle\"\n";
echo "                  />\n";
echo "                  <p class=\"text__catalog__card\">\n";
echo "                    EsonStyle (ЕсонСтайл) - фитнес<br />резинки\n";
echo "                  </p>\n";
echo "                  <p class=\"grey__text__catalog\">\n";
echo "                    Природная питьевая вода высшего<br />качества,\n";
echo "                    озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                  </p>\n";
echo "                </div>\n";
echo "                <!-- /.sup__info__card -->\n";
echo "                <div class=\"sub__info__card\">\n";
echo "                  <div class=\"money\">\n";
echo "                    <span class=\"money__discount\">220 ₽ </span\n";
echo "                    ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                  </div>\n";
echo "                  <!-- /.money -->\n";
echo "                  <div class=\"btn__money\">\n";
echo "                    <p class=\"plus\">+</p>\n";
echo "                    <p class=\"minus\">-</p>\n";
echo "                    <p class=\"counter\">0</p>\n";
echo "                    <a href=\"#\" class=\"btn__cart\"></a>\n";
echo "                  </div>\n";
echo "                  <!-- /.btn__money -->\n";
echo "                </div>\n";
echo "                <!-- /.sub__info__card -->\n";
echo "              </div>\n";
echo "              <!-- /.card__botlle -->\n";
echo "              <div class=\"card__botlle\">\n";
echo "                <div class=\"sup__info__card\">\n";
echo "                  <p class=\"round__hot\"></p>\n";
echo "                  <p class=\"round_percent\">%</p>\n";
echo "                  <img\n";
echo "                    src=\"./img/card__catalog.png\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"card_botlle\"\n";
echo "                  />\n";
echo "                  <p class=\"text__catalog__card\">\n";
echo "                    EsonStyle (ЕсонСтайл) - фитнес<br />резинки\n";
echo "                  </p>\n";
echo "                  <p class=\"grey__text__catalog\">\n";
echo "                    Природная питьевая вода высшего<br />качества,\n";
echo "                    озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                  </p>\n";
echo "                </div>\n";
echo "                <!-- /.sup__info__card -->\n";
echo "                <div class=\"sub__info__card\">\n";
echo "                  <div class=\"money\">\n";
echo "                    <span class=\"money__discount\">220 ₽ </span\n";
echo "                    ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                  </div>\n";
echo "                  <!-- /.money -->\n";
echo "                  <div class=\"btn__money\">\n";
echo "                    <p class=\"plus\">+</p>\n";
echo "                    <p class=\"minus\">-</p>\n";
echo "                    <p class=\"counter\">0</p>\n";
echo "                    <a href=\"#\" class=\"btn__cart\"></a>\n";
echo "                  </div>\n";
echo "                  <!-- /.btn__money -->\n";
echo "                </div>\n";
echo "                <!-- /.sub__info__card -->\n";
echo "              </div>\n";
echo "              <!-- /.card__botlle -->\n";
echo "              <div class=\"card__botlle\">\n";
echo "                <div class=\"sup__info__card\">\n";
echo "                  <p class=\"round__hot\"></p>\n";
echo "                  <p class=\"round_percent\">%</p>\n";
echo "                  <img\n";
echo "                    src=\"./img/card__catalog.png\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"card_botlle\"\n";
echo "                  />\n";
echo "                  <p class=\"text__catalog__card\">\n";
echo "                    EsonStyle (ЕсонСтайл) - фитнес<br />резинки\n";
echo "                  </p>\n";
echo "                  <p class=\"grey__text__catalog\">\n";
echo "                    Природная питьевая вода высшего<br />качества,\n";
echo "                    озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                  </p>\n";
echo "                </div>\n";
echo "                <!-- /.sup__info__card -->\n";
echo "                <div class=\"sub__info__card\">\n";
echo "                  <div class=\"money\">\n";
echo "                    <span class=\"money__discount\">220 ₽ </span\n";
echo "                    ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                  </div>\n";
echo "                  <!-- /.money -->\n";
echo "                  <div class=\"btn__money\">\n";
echo "                    <p class=\"plus\">+</p>\n";
echo "                    <p class=\"minus\">-</p>\n";
echo "                    <p class=\"counter\">0</p>\n";
echo "                    <a href=\"#\" class=\"btn__cart\"></a>\n";
echo "                  </div>\n";
echo "                  <!-- /.btn__money -->\n";
echo "                </div>\n";
echo "                <!-- /.sub__info__card -->\n";
echo "              </div>\n";
echo "              <!-- /.card__botlle -->\n";
echo "              <div class=\"card__botlle\">\n";
echo "                <div class=\"sup__info__card\">\n";
echo "                  <p class=\"round__hot\"></p>\n";
echo "                  <p class=\"round_percent\">%</p>\n";
echo "                  <img\n";
echo "                    src=\"./img/card__catalog.png\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"card_botlle\"\n";
echo "                  />\n";
echo "                  <p class=\"text__catalog__card\">\n";
echo "                    EsonStyle (ЕсонСтайл) - фитнес<br />резинки\n";
echo "                  </p>\n";
echo "                  <p class=\"grey__text__catalog\">\n";
echo "                    Природная питьевая вода высшего<br />качества,\n";
echo "                    озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                  </p>\n";
echo "                </div>\n";
echo "                <!-- /.sup__info__card -->\n";
echo "                <div class=\"sub__info__card\">\n";
echo "                  <div class=\"money\">\n";
echo "                    <span class=\"money__discount\">220 ₽ </span\n";
echo "                    ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                  </div>\n";
echo "                  <!-- /.money -->\n";
echo "                  <div class=\"btn__money\">\n";
echo "                    <p class=\"plus\">+</p>\n";
echo "                    <p class=\"minus\">-</p>\n";
echo "                    <p class=\"counter\">0</p>\n";
echo "                    <a href=\"#\" class=\"btn__cart\"></a>\n";
echo "                  </div>\n";
echo "                  <!-- /.btn__money -->\n";
echo "                </div>\n";
echo "                <!-- /.sub__info__card -->\n";
echo "              </div>\n";
echo "              <!-- /.card__botlle -->\n";
echo "\n";
echo "              <div class=\"card__botlle\">\n";
echo "                <div class=\"sup__info__card\">\n";
echo "                  <p class=\"round__hot\"></p>\n";
echo "                  <p class=\"round_percent\">%</p>\n";
echo "                  <img\n";
echo "                    src=\"./img/card__catalog.png\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"card_botlle\"\n";
echo "                  />\n";
echo "                  <p class=\"text__catalog__card\">\n";
echo "                    EsonStyle (ЕсонСтайл) - фитнес<br />резинки\n";
echo "                  </p>\n";
echo "                  <p class=\"grey__text__catalog\">\n";
echo "                    Природная питьевая вода высшего<br />качества,\n";
echo "                    озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                  </p>\n";
echo "                </div>\n";
echo "                <!-- /.sup__info__card -->\n";
echo "                <div class=\"sub__info__card\">\n";
echo "                  <div class=\"money\">\n";
echo "                    <span class=\"money__discount\">220 ₽ </span\n";
echo "                    ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                  </div>\n";
echo "                  <!-- /.money -->\n";
echo "                  <div class=\"btn__money\">\n";
echo "                    <p class=\"plus\">+</p>\n";
echo "                    <p class=\"minus\">-</p>\n";
echo "                    <p class=\"counter\">0</p>\n";
echo "                    <a href=\"#\" class=\"btn__cart\"></a>\n";
echo "                  </div>\n";
echo "                  <!-- /.btn__money -->\n";
echo "                </div>\n";
echo "                <!-- /.sub__info__card -->\n";
echo "              </div>\n";
echo "              <!-- /.card__botlle -->\n";
echo "              <div class=\"card__botlle\">\n";
echo "                <div class=\"sup__info__card\">\n";
echo "                  <p class=\"round__hot\"></p>\n";
echo "                  <p class=\"round_percent\">%</p>\n";
echo "                  <img\n";
echo "                    src=\"./img/card__catalog.png\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"card_botlle\"\n";
echo "                  />\n";
echo "                  <p class=\"text__catalog__card\">\n";
echo "                    EsonStyle (ЕсонСтайл) - фитнес<br />резинки\n";
echo "                  </p>\n";
echo "                  <p class=\"grey__text__catalog\">\n";
echo "                    Природная питьевая вода высшего<br />качества,\n";
echo "                    озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                  </p>\n";
echo "                </div>\n";
echo "                <!-- /.sup__info__card -->\n";
echo "                <div class=\"sub__info__card\">\n";
echo "                  <div class=\"money\">\n";
echo "                    <span class=\"money__discount\">220 ₽ </span\n";
echo "                    ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                  </div>\n";
echo "                  <!-- /.money -->\n";
echo "                  <div class=\"btn__money\">\n";
echo "                    <p class=\"plus\">+</p>\n";
echo "                    <p class=\"minus\">-</p>\n";
echo "                    <p class=\"counter\">0</p>\n";
echo "                    <a href=\"#\" class=\"btn__cart\"></a>\n";
echo "                  </div>\n";
echo "                  <!-- /.btn__money -->\n";
echo "                </div>\n";
echo "                <!-- /.sub__info__card -->\n";
echo "              </div>\n";
echo "              <!-- /.card__botlle -->\n";
echo "              <div class=\"card__botlle\">\n";
echo "                <div class=\"sup__info__card\">\n";
echo "                  <p class=\"round__hot\"></p>\n";
echo "                  <p class=\"round_percent\">%</p>\n";
echo "                  <img\n";
echo "                    src=\"./img/card__catalog.png\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"card_botlle\"\n";
echo "                  />\n";
echo "                  <p class=\"text__catalog__card\">\n";
echo "                    EsonStyle (ЕсонСтайл) - фитнес<br />резинки\n";
echo "                  </p>\n";
echo "                  <p class=\"grey__text__catalog\">\n";
echo "                    Природная питьевая вода высшего<br />качества,\n";
echo "                    озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                  </p>\n";
echo "                </div>\n";
echo "                <!-- /.sup__info__card -->\n";
echo "                <div class=\"sub__info__card\">\n";
echo "                  <div class=\"money\">\n";
echo "                    <span class=\"money__discount\">220 ₽ </span\n";
echo "                    ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                  </div>\n";
echo "                  <!-- /.money -->\n";
echo "                  <div class=\"btn__money\">\n";
echo "                    <p class=\"plus\">+</p>\n";
echo "                    <p class=\"minus\">-</p>\n";
echo "                    <p class=\"counter\">0</p>\n";
echo "                    <a href=\"#\" class=\"btn__cart\"></a>\n";
echo "                  </div>\n";
echo "                  <!-- /.btn__money -->\n";
echo "                </div>\n";
echo "                <!-- /.sub__info__card -->\n";
echo "              </div>\n";
echo "              <!-- /.card__botlle -->\n";
echo "              <div class=\"card__botlle\">\n";
echo "                <div class=\"sup__info__card\">\n";
echo "                  <p class=\"round__hot\"></p>\n";
echo "                  <p class=\"round_percent\">%</p>\n";
echo "                  <img\n";
echo "                    src=\"./img/card__catalog.png\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"card_botlle\"\n";
echo "                  />\n";
echo "                  <p class=\"text__catalog__card\">\n";
echo "                    EsonStyle (ЕсонСтайл) - фитнес<br />резинки\n";
echo "                  </p>\n";
echo "                  <p class=\"grey__text__catalog\">\n";
echo "                    Природная питьевая вода высшего<br />качества,\n";
echo "                    озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                  </p>\n";
echo "                </div>\n";
echo "                <!-- /.sup__info__card -->\n";
echo "                <div class=\"sub__info__card\">\n";
echo "                  <div class=\"money\">\n";
echo "                    <span class=\"money__discount\">220 ₽ </span\n";
echo "                    ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                  </div>\n";
echo "                  <!-- /.money -->\n";
echo "                  <div class=\"btn__money\">\n";
echo "                    <p class=\"plus\">+</p>\n";
echo "                    <p class=\"minus\">-</p>\n";
echo "                    <p class=\"counter\">0</p>\n";
echo "                    <a href=\"#\" class=\"btn__cart\"></a>\n";
echo "                  </div>\n";
echo "                  <!-- /.btn__money -->\n";
echo "                </div>\n";
echo "                <!-- /.sub__info__card -->\n";
echo "              </div>\n";
echo "              <!-- /.card__botlle -->\n";
echo "              <div class=\"card__botlle side_sett\">\n";
echo "                <div class=\"sup__info__card\">\n";
echo "                  <p class=\"round__hot\"></p>\n";
echo "                  <p class=\"round_percent\">%</p>\n";
echo "                  <img\n";
echo "                    src=\"./img/card__catalog.png\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"card_botlle\"\n";
echo "                  />\n";
echo "                  <p class=\"text__catalog__card\">\n";
echo "                    EsonStyle (ЕсонСтайл) - фитнес<br />резинки\n";
echo "                  </p>\n";
echo "                  <p class=\"grey__text__catalog\">\n";
echo "                    Природная питьевая вода высшего<br />качества,\n";
echo "                    озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                  </p>\n";
echo "                </div>\n";
echo "                <!-- /.sup__info__card -->\n";
echo "                <div class=\"sub__info__card\">\n";
echo "                  <div class=\"money\">\n";
echo "                    <span class=\"money__discount\">220 ₽ </span\n";
echo "                    ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                  </div>\n";
echo "                  <!-- /.money -->\n";
echo "                  <div class=\"btn__money\">\n";
echo "                    <p class=\"plus\">+</p>\n";
echo "                    <p class=\"minus\">-</p>\n";
echo "                    <p class=\"counter\">0</p>\n";
echo "                    <a href=\"#\" class=\"btn__cart\"></a>\n";
echo "                    <div class=\"wrapp_backet\">\n";
echo "                      <div class=\"side__basket\">\n";
echo "                        <a href=\"#\" class=\"basket__catalog\"></a>\n";
echo "                        <span class=\"span_numb_bask\">4</span>\n";
echo "                      </div>\n";
echo "                    </div>\n";
echo "                    <!-- /.wrapp_backet -->\n";
echo "                  </div>\n";
echo "                  <!-- /.btn__money -->\n";
echo "                </div>\n";
echo "                <!-- /.sub__info__card -->\n";
echo "              </div>\n";
echo "              <!-- /.card__botlle -->\n";
echo "            </div>\n";
echo "            \n";
echo "            <div class=\"full\">\n";
echo "              <a class=\"btn__full_catalog\">Полный каталог</a>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <!-- /.card__catalog -->\n";
echo "          <div class=\"bg_modal\">\n";
echo "            <div class=\"modal__catalog_wrapp\">\n";
echo "              <div class=\"modal__catalog\">\n";
echo "                <div class=\"wrapp_close\">\n";
echo "                  <h3 class=\"mod__cat\">Быстрый заказ</h3>\n";
echo "                  <a href=\"#\" class=\"close__modal_wind\"></a>\n";
echo "                </div>\n";
echo "                <div class=\"basket__strip\">\n";
echo "                  <div class=\"block_mod_img\">\n";
echo "                    <img\n";
echo "                      src=\"./img/icon/botmod.svg\"\n";
echo "                      alt=\"img\"\n";
echo "                      class=\"bott_mod\"\n";
echo "                    />\n";
echo "                  </div>\n";
echo "                  <!-- /.block_mod_img -->\n";
echo "                  <div class=\"text_mod_strip\">\n";
echo "                    <h3 class=\"title_prod_mod\">\n";
echo "                      EsonStyle (ЕсонСтайл)<br />- фитнес резинки\n";
echo "                    </h3>\n";
echo "                    <p class=\"text_mod_prod\">\n";
echo "                      Природная питьевая вода высшего<br />качества,\n";
echo "                      озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                    </p>\n";
echo "                  </div>\n";
echo "                  <!-- /.text_mod_strip -->\n";
echo "                  <div class=\"counter_mod\">\n";
echo "                    <p class=\"round_lite\"></p>\n";
echo "                    <p class=\"round_lite_proc\">%</p>\n";
echo "                    <p class=\"counter sett_left\">0</p>\n";
echo "                    <p class=\"plus__modal\">+</p>\n";
echo "                    <p class=\"minus__modal\">-</p>\n";
echo "                    <div class=\"money sett__money\">\n";
echo "                      <span class=\"money__discount\">220 ₽ </span\n";
echo "                      ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                    </div>\n";
echo "                    <!-- /.money -->\n";
echo "                    <a href=\"#\" class=\"close__strip\"></a>\n";
echo "                  </div>\n";
echo "                  <!-- /.counter_mod -->\n";
echo "                </div>\n";
echo "                <!-- /.basket__strip -->\n";
echo "                <div class=\"basket__strip\">\n";
echo "                  <div class=\"block_mod_img\">\n";
echo "                    <img\n";
echo "                      src=\"./img/icon/botmod.svg\"\n";
echo "                      alt=\"img\"\n";
echo "                      class=\"bott_mod\"\n";
echo "                    />\n";
echo "                  </div>\n";
echo "                  <!-- /.block_mod_img -->\n";
echo "                  <div class=\"text_mod_strip\">\n";
echo "                    <h3 class=\"title_prod_mod\">\n";
echo "                      EsonStyle (ЕсонСтайл)<br />- фитнес резинки\n";
echo "                    </h3>\n";
echo "                    <p class=\"text_mod_prod\">\n";
echo "                      Природная питьевая вода высшего<br />качества,\n";
echo "                      озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                    </p>\n";
echo "                  </div>\n";
echo "                  <!-- /.text_mod_strip -->\n";
echo "                  <div class=\"counter_mod\">\n";
echo "                    <p class=\"round_lite\"></p>\n";
echo "                    <p class=\"round_lite_proc\">%</p>\n";
echo "                    <p class=\"counter sett_left\">0</p>\n";
echo "                    <p class=\"plus__modal\">+</p>\n";
echo "                    <p class=\"minus__modal\">-</p>\n";
echo "                    <div class=\"money sett__money\">\n";
echo "                      <span class=\"money__discount\">220 ₽ </span\n";
echo "                      ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                    </div>\n";
echo "                    <!-- /.money -->\n";
echo "                    <a href=\"#\" class=\"close__strip\"></a>\n";
echo "                  </div>\n";
echo "                  <!-- /.counter_mod -->\n";
echo "                </div>\n";
echo "                <!-- /.basket__strip -->\n";
echo "                <div class=\"basket__strip\">\n";
echo "                  <div class=\"block_mod_img\">\n";
echo "                    <img\n";
echo "                      src=\"./img/icon/botmod.svg\"\n";
echo "                      alt=\"img\"\n";
echo "                      class=\"bott_mod\"\n";
echo "                    />\n";
echo "                  </div>\n";
echo "                  <!-- /.block_mod_img -->\n";
echo "                  <div class=\"text_mod_strip\">\n";
echo "                    <h3 class=\"title_prod_mod\">\n";
echo "                      EsonStyle (ЕсонСтайл)<br />- фитнес резинки\n";
echo "                    </h3>\n";
echo "                    <p class=\"text_mod_prod\">\n";
echo "                      Природная питьевая вода высшего<br />качества,\n";
echo "                      озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                    </p>\n";
echo "                  </div>\n";
echo "                  <!-- /.text_mod_strip -->\n";
echo "                  <div class=\"counter_mod\">\n";
echo "                    <p class=\"round_lite\"></p>\n";
echo "                    <p class=\"round_lite_proc\">%</p>\n";
echo "                    <p class=\"counter sett_left\">0</p>\n";
echo "                    <p class=\"plus__modal\">+</p>\n";
echo "                    <p class=\"minus__modal\">-</p>\n";
echo "                    <div class=\"money sett__money\">\n";
echo "                      <span class=\"money__discount\">220 ₽ </span\n";
echo "                      ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                    </div>\n";
echo "                    <!-- /.money -->\n";
echo "                    <a href=\"#\" class=\"close__strip\"></a>\n";
echo "                  </div>\n";
echo "                  <!-- /.counter_mod -->\n";
echo "                </div>\n";
echo "                <!-- /.basket__strip -->\n";
echo "                <div class=\"basket__strip\">\n";
echo "                  <div class=\"block_mod_img\">\n";
echo "                    <img\n";
echo "                      src=\"./img/icon/botmod.svg\"\n";
echo "                      alt=\"img\"\n";
echo "                      class=\"bott_mod\"\n";
echo "                    />\n";
echo "                  </div>\n";
echo "                  <!-- /.block_mod_img -->\n";
echo "                  <div class=\"text_mod_strip\">\n";
echo "                    <h3 class=\"title_prod_mod\">\n";
echo "                      EsonStyle (ЕсонСтайл)<br />- фитнес резинки\n";
echo "                    </h3>\n";
echo "                    <p class=\"text_mod_prod\">\n";
echo "                      Природная питьевая вода высшего<br />качества,\n";
echo "                      озонированная, рекомендована<br />детям от 3-х лет\n";
echo "                    </p>\n";
echo "                  </div>\n";
echo "                  <!-- /.text_mod_strip -->\n";
echo "                  <div class=\"counter_mod\">\n";
echo "                    <p class=\"round_lite\"></p>\n";
echo "                    <p class=\"round_lite_proc\">%</p>\n";
echo "                    <p class=\"counter sett_left\">0</p>\n";
echo "                    <p class=\"plus__modal\">+</p>\n";
echo "                    <p class=\"minus__modal\">-</p>\n";
echo "                    <div class=\"money sett__money\">\n";
echo "                      <span class=\"money__discount\">220 ₽ </span\n";
echo "                      ><span class=\"money__nodiscount\">399 ₽</span>\n";
echo "                    </div>\n";
echo "                    <!-- /.money -->\n";
echo "                    <a href=\"#\" class=\"close__strip\"></a>\n";
echo "                  </div>\n";
echo "                  <!-- /.counter_mod -->\n";
echo "                </div>\n";
echo "                <!-- /.basket__strip -->\n";
echo "              </div>\n";
echo "              <!-- /.modal__catalog -->\n";
echo "              <div class=\"form__modal\">\n";
echo "                <form action=\"#\" class=\"form_bran_pan\">\n";
echo "                  <div class=\"cont_input\">\n";
echo "                    <input\n";
echo "                      type=\"text\"\n";
echo "                      class=\"panel_bran\"\n";
echo "                      placeholder=\"Ваше имя\"\n";
echo "                    />\n";
echo "                    <input\n";
echo "                      type=\"text\"\n";
echo "                      class=\"panel_bran\"\n";
echo "                      placeholder=\"Ваш телефон\"\n";
echo "                    />\n";
echo "                  </div>\n";
echo "                  <!-- /.cont_input -->\n";
echo "                  <div class=\"btn__ckeckid\">\n";
echo "                    <a href=\"\" class=\"btn_panel_bran_open\">Перезвоните мне</a>\n";
echo "                    <div class=\"check_box\">\n";
echo "                      <label class=\"label\"\n";
echo "                        ><input type=\"checkbox\" class=\"checkbox\" />\n";
echo "                        <span class=\"fake\"></span>\n";
echo "                        <span class=\"text_chek_panel\"\n";
echo "                          ><span class=\"text__check\"\n";
echo "                            >Согласие на обработку </span\n";
echo "                          ><span class=\"text__check_sub\"\n";
echo "                            >персональных данных</span\n";
echo "                          ></span\n";
echo "                        ></label\n";
echo "                      >\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                </form>\n";
echo "                <!-- /.form_bran_panel -->\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <!-- /.modal__catalog_wrapp -->\n";
echo "          </div>\n";
echo "          <div class=\"bg__modal_two\">\n";
echo "            <div class=\"modal_thank\">\n";
echo "              <a href=\"#\" class=\"close_thank\"></a>\n";
echo "              <img\n";
echo "                src=\"./img/icon/shoppingcartBig.svg\"\n";
echo "                alt=\"\"\n";
echo "                class=\"cart_thank\"\n";
echo "              />\n";
echo "              <p class=\"text_thank\">\n";
echo "                Спасибо, Ваш товар добавлен<br />в корзину!\n";
echo "              </p>\n";
echo "              <div class=\"block_btn_thank\">\n";
echo "                <a href=\"\" class=\"proceed\">Продолжить покупки</a>\n";
echo "                <a href=\"\" class=\"issue\">Оформить заказ</a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"modal__free_bg\">\n";
echo "            <div class=\"wrapp__free\">\n";
echo "              <div class=\"modal__free\">\n";
echo "                <span class=\"on\"></span>\n";
echo "                <p class=\"text_on\">Заявка принята</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </section>\n";
echo "      <!-- /.catalog -->\n";
echo "      <section class=\"our__service\">\n";
echo "        <div class=\"container\">\n";
echo "          <div class=\"block_panel-cont\">\n";
echo "            <div class=\"wrapp__panel\">\n";
echo "              <div class=\"block__panel_our\">\n";
echo "                <div class=\"block__content\">\n";
echo "                  <div class=\"text__content\">\n";
echo "                    <h2 class=\"title__our\">Вулканическое происхождение</h2>\n";
echo "                    <p class=\"text__our\">\n";
echo "                      Слабоминерализованная вода заволжского водоносного горизонта\n";
echo "                      имеет сульфанный<br />натриево-магниево-кальциевый состав со\n";
echo "                      слабощелочной реакцией среды (pH 7,3 - 7,5) и<br />минерализацией\n";
echo "                      в диапазоне 3,5 - 3,8 г/дм3.\n";
echo "                    </p>\n";
echo "                    <div class=\"panel__tabs\">\n";
echo "                      <div class=\"tab set__tab__one\">\n";
echo "                        <p class=\"namb__title\">1500</p>\n";
echo "                        <p class=\"text__tab\">Лет в недрах</p>\n";
echo "                      </div>\n";
echo "                      <div class=\"tab\">\n";
echo "                        <p class=\"namb__title\">8-10 км</p>\n";
echo "                        <p class=\"text__tab\">глубина скважин</p>\n";
echo "                      </div>\n";
echo "                      <div class=\"tab sett-tab\">\n";
echo "                        <p class=\"namb__title\">60</p>\n";
echo "                        <p class=\"text__tab\">минералов в составе</p>\n";
echo "                      </div>\n";
echo "                    </div>\n";
echo "                    <!-- /.panel__tabs -->\n";
echo "                  </div>\n";
echo "                  <!-- /.text__content -->\n";
echo "                </div>\n";
echo "                <!-- /.block__content -->\n";
echo "                <div class=\"block__img__panel\"></div>\n";
echo "                <!-- /.block__img__panel -->\n";
echo "              </div>\n";
echo "              <!-- /.block__panel_our -->\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <!-- /.block_panel-cont -->\n";
echo "          <div class=\"our__servic\">\n";
echo "            <h2 class=\"title__card__prod\">Наши услуги</h2>\n";
echo "            <div class=\"card__our\">\n";
echo "              <div class=\"strip__one\">\n";
echo "                <a class=\"link_site\" href=\"./spill.html\"\n";
echo "                  ><div class=\"card__our__prod\">\n";
echo "                    <div class=\"img__prod\">\n";
echo "                      <img\n";
echo "                        src=\"./img/icon/water-bottle1.svg\"\n";
echo "                        alt=\"\"\n";
echo "                        class=\"prod__img\"\n";
echo "                      />\n";
echo "                      <span class=\"back_round\">%</span>\n";
echo "                    </div>\n";
echo "                    <div class=\"cont__prod\">\n";
echo "                      <h4 class=\"title__prod\">Брендирование воды</h4>\n";
echo "                      <p class=\"text__prod\">\n";
echo "                        Фирменные бутылки с водой - это проверенный<br />способ\n";
echo "                        повысить свой профессиональный имидж и<br />бренд.\n";
echo "                      </p>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                  <!-- /.card__our__prod --></a\n";
echo "                >\n";
echo "                <div class=\"card__our__prod\">\n";
echo "                  <div class=\"img__prod\">\n";
echo "                    <img\n";
echo "                      src=\"./img/icon/water1.svg\"\n";
echo "                      alt=\"\"\n";
echo "                      class=\"prod__img\"\n";
echo "                    />\n";
echo "                  </div>\n";
echo "                  <div class=\"cont__prod\">\n";
echo "                    <h4 class=\"title__prod\">Контрактный розлив</h4>\n";
echo "                    <p class=\"text__prod\">\n";
echo "                      Планируете наладить контрактное производство<br />напитков\n";
echo "                      на мощностях партнеров? Тогда это<br />предложение для\n";
echo "                      вас.\n";
echo "                    </p>\n";
echo "                  </div>\n";
echo "                </div>\n";
echo "                <!-- /.card__our__prod -->\n";
echo "                <div class=\"card__our__prod\">\n";
echo "                  <div class=\"img__prod\">\n";
echo "                    <img src=\"./img/icon/pump1.svg\" alt=\"\" class=\"prod__img\" />\n";
echo "                  </div>\n";
echo "                  <div class=\"cont__prod\">\n";
echo "                    <h4 class=\"title__prod\">Вода на розлив</h4>\n";
echo "                    <p class=\"text__prod\">\n";
echo "                      Так как в этом случае нет нужды устанавливать<br />дорогостоящее\n";
echo "                      и сложное в обслуживании<br />водоочистное оборудование.\n";
echo "                    </p>\n";
echo "                    <div class=\"link__stripe\">\n";
echo "                      <a href=\"#\" class=\"prod\">Артезианская </a\n";
echo "                      ><a href=\"#\" class=\"prod strip\">СТМ</a>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                </div>\n";
echo "                <!-- /.card__our__prod -->\n";
echo "                <div class=\"card__our__prod\">\n";
echo "                  <div class=\"img__prod\">\n";
echo "                    <img\n";
echo "                      src=\"./img/icon/plastic1.svg\"\n";
echo "                      alt=\"\"\n";
echo "                      class=\"prod__img\"\n";
echo "                    />\n";
echo "                  </div>\n";
echo "                  <div class=\"cont__prod\">\n";
echo "                    <h4 class=\"title__prod\">Изготовление ПЭТ тары</h4>\n";
echo "                    <p class=\"text__prod\">\n";
echo "                      Бутылки из прозрачного зеленого стекла для вина и<br />других\n";
echo "                      жидкостей оптом и под заказ. Винная<br />бутылка 0,75\n";
echo "                      литра (зеленое стекло).\n";
echo "                    </p>\n";
echo "                    <div class=\"link__strip__two\">\n";
echo "                      <a href=\"#\" class=\"strip__prod\">Бутылки оптом </a\n";
echo "                      ><a href=\"#\" class=\"strip__prod\">19 литров </a\n";
echo "                      ><a href=\"#\" class=\"strip__prod\">5 литров</a>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                </div>\n";
echo "                <!-- /.card__our__prod -->\n";
echo "                <div class=\"card__our__prod sett__marg\">\n";
echo "                  <div class=\"img__prod\">\n";
echo "                    <img\n";
echo "                      src=\"./img/icon/water1.svg\"\n";
echo "                      alt=\"\"\n";
echo "                      class=\"prod__img\"\n";
echo "                    />\n";
echo "                  </div>\n";
echo "                  <div class=\"cont__prod\">\n";
echo "                    <h4 class=\"title__prod\">Вода оптом</h4>\n";
echo "                    <p class=\"text__prod\">\n";
echo "                      Бутылки из прозрачного зеленого стекла для вина и<br />других\n";
echo "                      жидкостей оптом и под заказ. Винная<br />бутылка 0,75\n";
echo "                      литра (зеленое стекло).\n";
echo "                    </p>\n";
echo "                    <div class=\"prod__center\">\n";
echo "                      <div class=\"left__strip\">\n";
echo "                        <a href=\"#\" class=\"strip__prod\">Минеральная </a\n";
echo "                        ><a href=\"#\" class=\"strip__prod\">Газированная </a\n";
echo "                        ><a href=\"#\" class=\"strip__prod\">Артезианская</a>\n";
echo "                      </div>\n";
echo "                      <div class=\"right__strip\">\n";
echo "                        <a href=\"#\" class=\"strip__prod\">Элитная </a\n";
echo "                        ><a href=\"#\" class=\"strip__prod\">5 литров </a\n";
echo "                        ><a href=\"#\" class=\"strip__prod\">19 литров</a>\n";
echo "                      </div>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                </div>\n";
echo "                <!-- /.card__our__prod -->\n";
echo "                <div class=\"card__our__prod\">\n";
echo "                  <div class=\"img__prod\">\n";
echo "                    <img\n";
echo "                      src=\"./img/icon/water1.svg\"\n";
echo "                      alt=\"\"\n";
echo "                      class=\"prod__img\"\n";
echo "                    />\n";
echo "                  </div>\n";
echo "                  <div class=\"cont__prod\">\n";
echo "                    <h4 class=\"title__prod\">Контрактный розлив</h4>\n";
echo "                    <p class=\"text__prod\">\n";
echo "                      Бутылки из прозрачного зеленого стекла для вина и<br />других\n";
echo "                      жидкостей оптом и под заказ. Винная<br />бутылка 0,75\n";
echo "                      литра (зеленое стекло).\n";
echo "                    </p>\n";
echo "                    <div class=\"prod__center\">\n";
echo "                      <div class=\"left__strip\">\n";
echo "                        <a href=\"#\" class=\"strip__prod\">Лимонад </a\n";
echo "                        ><a href=\"#\" class=\"strip__prod\">Квас</a>\n";
echo "                      </div>\n";
echo "                      <div class=\"right__strip\">\n";
echo "                        <a href=\"#\" class=\"strip__prod\">Морс </a\n";
echo "                        ><a href=\"#\" class=\"strip__prod\">Безалкогольные</a>\n";
echo "                      </div>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                </div>\n";
echo "                <!-- /.card__our__prod -->\n";
echo "                <div class=\"card__our__prod sett__mard_b\">\n";
echo "                  <div class=\"img__prod\">\n";
echo "                    <img\n";
echo "                      src=\"./img/icon/water-bottle1.svg\"\n";
echo "                      alt=\"\"\n";
echo "                      class=\"prod__img\"\n";
echo "                    />\n";
echo "                    <span class=\"back_round\">%</span>\n";
echo "                  </div>\n";
echo "                  <div class=\"cont__prod\">\n";
echo "                    <h4 class=\"title__prod\">Вода на розлив</h4>\n";
echo "                    <p class=\"text__prod\">\n";
echo "                      Бутылки из прозрачного зеленого стекла для вина и<br />других\n";
echo "                      жидкостей оптом и под заказ. Винная<br />бутылка 0,75\n";
echo "                      литра\n";
echo "                    </p>\n";
echo "                    <div class=\"link__stripe\">\n";
echo "                      <a href=\"#\" class=\"prod\">Берегиня</a>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                </div>\n";
echo "                <!-- /.card__our__prod -->\n";
echo "              </div>\n";
echo "              <!-- /.strip__one -->\n";
echo "              \n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <!-- /.card__our -->\n";
echo "          </div>\n";
echo "          <!-- /.our__servic -->\n";
echo "        </div>\n";
echo "      </section>\n";
echo "      <!-- /.our__service -->\n";
echo "\n";
echo "      <section class=\"factory__showing\">\n";
echo "        <div class=\"container\">\n";
echo "          <div class=\"block__ifo\">\n";
echo "            <h1 class=\"title__show\">Завод минеральных вод «Берегиня»</h1>\n";
echo "            <div class=\"wrapp__ifo\">\n";
echo "              <div class=\"block__ifo__left\">\n";
echo "                <p class=\"text_ifo_block\">\n";
echo "                  Завод минеральных вод «Берегиня» был введен в эксплуатацию в\n";
echo "                  1995 году на месте<br />высоко минерализированной скважины №\n";
echo "                  3/78 глубиной 600 метров — уникального<br />природного\n";
echo "                  источника, геологический возраст которого — 400-345 млн. лет\n";
echo "                  —<br />соответствует Девонскому периоду Палеозойской эры. На\n";
echo "                  базе данного<br />месторождения с 1937 года успешно\n";
echo "                  функционирует санаторий «Раменское»,<br />специализирующийся\n";
echo "                  на лечении различных заболеваний с применением<br />бальнеологических\n";
echo "                  процедур.\n";
echo "                </p>\n";
echo "                <img src=\"./img/Rectangle106.png\" alt=\"img\" class=\"ifo__img\" />\n";
echo "              </div>\n";
echo "              <!-- /.block__ifo__left -->\n";
echo "              <div class=\"block__ifo__right\">\n";
echo "                <p class=\"text_ifo_block\">\n";
echo "                  Вода из этого месторождения является основой для производства\n";
echo "                  минеральных и<br />лечебно-столовых вод «Берегиня» и\n";
echo "                  «Берегиня-1» с различной степенью<br />минерализации. Впервые\n";
echo "                  в Подмосковье для практического использования получена<br />минеральная\n";
echo "                  вода в большом количестве при самоизливе, не требующая<br />принудительной\n";
echo "                  подачи. На том же месте в 2005 году введена в эксплуатацию<br />артезианская\n";
echo "                  скважина ГВК-1 (46211725) глубиной 100 м.\n";
echo "                </p>\n";
echo "                <div class=\"sup__img__ifo\">\n";
echo "                  <img\n";
echo "                    src=\"./img/Rectangle107.png\"\n";
echo "                    alt=\"\"\n";
echo "                    class=\"ifo_sup_img\"\n";
echo "                  />\n";
echo "                  <img\n";
echo "                    src=\"./img/Rectangle108.png\"\n";
echo "                    alt=\"\"\n";
echo "                    class=\"ifo_sup_img\"\n";
echo "                  />\n";
echo "                </div>\n";
echo "                <div class=\"sub__img__ifo\">\n";
echo "                  <img\n";
echo "                    src=\"./img/Rectangle109.png\"\n";
echo "                    alt=\"\"\n";
echo "                    class=\"ifo_sub_img\"\n";
echo "                  />\n";
echo "                  <img\n";
echo "                    src=\"./img/Rectangle110.png\"\n";
echo "                    alt=\"\"\n";
echo "                    class=\"ifo_sub_img\"\n";
echo "                  />\n";
echo "                </div>\n";
echo "              </div>\n";
echo "              <!-- /.block__ifo__right -->\n";
echo "            </div>\n";
echo "            <p class=\"text__all\">\n";
echo "              Технология приготовления питьевой воды имеет значительное\n";
echo "              преимущество перед существующими технологиями, применяемыми на\n";
echo "              городских водозаборных станциях, т.к.<br />не предусматривает\n";
echo "              использование химических реагентов. Подземные воды, каптируемые\n";
echo "              скважинами (глубиной 600 м и 98,5 м), с целью окисления\n";
echo "              присутствующих в них<br />железа и удаления газов, улучшения\n";
echo "              органолептических показателей и удаления патогенных\n";
echo "              микроорганизмов подвергаются очистке на кварцевых, угольных\n";
echo "              фильтрах и<br />фильтрах обезжелезования с последующей обработкой\n";
echo "              бактерицидными лампами,и розливаются в 0,6л, 1л, 1,5л, 2л и 19 л\n";
echo "              тару в соответствии с Санитарно-гигиеническими<br />требованиями\n";
echo "              РФ. На последней ступени подготовки воды перед непосредственным\n";
echo "              розливом используются фильтры тонкой очистки толщиной 1 микрон.<br />Все\n";
echo "              стадии производства проходят контроль в Российских и Московских\n";
echo "              органах стандартизации, лицензирования и сертификации.\n";
echo "            </p>\n";
echo "          </div>\n";
echo "          <div class=\"block__card__factory\">\n";
echo "            <div class=\"card__factory\">\n";
echo "              <p class=\"text__factory\">Санаторий «Раменское»</p>\n";
echo "              <div class=\"wrapp_med\">\n";
echo "                <a href=\"\" class=\"btn__factory\">Подробнее</a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <!-- /.card__factory -->\n";
echo "            <div class=\"card__factory__one\">\n";
echo "              <p class=\"text__factory\">Скважина завода «Берегиня»</p>\n";
echo "              <div class=\"wrapp_med\">\n";
echo "                <a href=\"\" class=\"btn__factory\">Подробнее</a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <!-- /.card__factory -->\n";
echo "            <div class=\"card__factory__two\">\n";
echo "              <p class=\"text__factory\">\n";
echo "                Цех по производству воды в <br />бутылках 0,6л - 1,5л\n";
echo "              </p>\n";
echo "              <div class=\"wrapp_med\">\n";
echo "                <a href=\"\" class=\"btn__factory\">Подробнее</a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <!-- /.card__factory -->\n";
echo "            <div class=\"card__factory__free\">\n";
echo "              <p class=\"text__factory\">\n";
echo "                Цех по производству воды в <br />бутылях 5л\n";
echo "              </p>\n";
echo "              <div class=\"wrapp_med\">\n";
echo "                <a href=\"\" class=\"btn__factory\">Подробнее</a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <!-- /.card__factory -->\n";
echo "            <div class=\"card__factory__four\">\n";
echo "              <p class=\"text__factory\">\n";
echo "                Цех по производству воды в <br />бутылях 19л\n";
echo "              </p>\n";
echo "              <div class=\"wrapp_med\">\n";
echo "                <a href=\"\" class=\"btn__factory\">Подробнее</a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <!-- /.card__factory -->\n";
echo "            <div class=\"card__factory_five\">\n";
echo "              <p class=\"text__factory\">\n";
echo "                Артезианская скважина завода <br />«Берегиня» ГВК № 1\n";
echo "              </p>\n";
echo "              <div class=\"wrapp_med\">\n";
echo "                <a href=\"\" class=\"btn__factory\">Подробнее</a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <!-- /.card__factory -->\n";
echo "          </div>\n";
echo "          <!-- /.block__card__factory -->\n";
echo "        </div>\n";
echo "        <!-- /.container -->\n";
echo "      </section>\n";
echo "      <!-- /.factory__showing -->\n";
echo "\n";
echo "      <section class=\"our__clients\">\n";
echo "        <div class=\"container\">\n";
echo "          <div class=\"panel__people__wrapp\">\n";
echo "            <h1 class=\"title__people\">Отзывы наших клиентов</h1>\n";
echo "            <div class=\"panel__people\">\n";
echo "              <div class=\"panel__people__left\">\n";
echo "                <div class=\"left__people\">\n";
echo "                  <img src=\"./img/Igor.png\" alt=\"img\" class=\"people\" />\n";
echo "                  <img\n";
echo "                    src=\"./img/icon/123.svg\"\n";
echo "                    alt=\"icon\"\n";
echo "                    class=\"icon__people\"\n";
echo "                  />\n";
echo "                </div>\n";
echo "                <!-- /.left__people -->\n";
echo "                <div class=\"info__people\">\n";
echo "                  <h2 class=\"title__people_panel\">Игорь Рыбаков</h2>\n";
echo "                  <p class=\"sub__text__people\">\n";
echo "                    совладелец корпорации Технониколь и<br />сооснователь\n";
echo "                    Рыбаков Фонд.\n";
echo "                  </p>\n";
echo "                  <p class=\"all__people__text sett__text_peop\">\n";
echo "                    В особенности же постоянный количественный рост и сфера\n";
echo "                    нашей<br />активности влечет за собой процесс внедрения и\n";
echo "                    модернизации<br />системы обучения кадров, соответствует\n";
echo "                    насущным потребностям.\n";
echo "                  </p>\n";
echo "                  <p class=\"all__people__text\">\n";
echo "                    Значимость этих проблем настолько очевидна, что начало<br />повседневной\n";
echo "                    работы по формированию позиции требуют<br />определения и\n";
echo "                    уточнения соответствующий условий активизации.\n";
echo "                  </p>\n";
echo "                </div>\n";
echo "                <!-- /.info__people -->\n";
echo "              </div>\n";
echo "              <!-- /.panel__people__left -->\n";
echo "              <div class=\"wrapp_bg\">\n";
echo "                <div class=\"panel__people__right bg__sett\">\n";
echo "                  <div class=\"block__people__Left\">\n";
echo "                    <div class=\"block__oscar\">\n";
echo "                      <div class=\"oscar__img\">\n";
echo "                        <img\n";
echo "                          src=\"./img/icon/1234.svg\"\n";
echo "                          alt=\"icon\"\n";
echo "                          class=\"icon__oscar\"\n";
echo "                        />\n";
echo "                      </div>\n";
echo "                      <p class=\"text__youtube\">\n";
echo "                        Смотреть видеоотзыв<br />на youtube.com\n";
echo "                      </p>\n";
echo "                      <div class=\"content__oscar\">\n";
echo "                        <h3 class=\"title_pos\">Оскар Хартман</h3>\n";
echo "                        <p class=\"text__pos\">\n";
echo "                          серийный предприниматель, сооснователь<br />проектов\n";
echo "                          KupiVIP.ru, Carprice, CarFix\n";
echo "                        </p>\n";
echo "                        <div class=\"youtube__shape\">\n";
echo "                          <div class=\"shape__one\">\n";
echo "                            <div class=\"shape__two\">\n";
echo "                              <div class=\"shape__free\">\n";
echo "                                <a href=\"#\" class=\"play__shape\"></a>\n";
echo "                              </div>\n";
echo "                              <!-- /.shape__free -->\n";
echo "                            </div>\n";
echo "                            <!-- /.shape__two -->\n";
echo "                          </div>\n";
echo "                          <!-- /.shape__one -->\n";
echo "                        </div>\n";
echo "                      </div>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                </div>\n";
echo "                <!-- /.panel__people__right -->\n";
echo "              </div>\n";
echo "              <!-- /.wrapp_bg -->\n";
echo "            </div>\n";
echo "            <!-- /.panel__people -->\n";
echo "          </div>\n";
echo "          <!-- /.panel__people -->\n";
echo "        </div>\n";
echo "      </section>\n";
echo "      <!-- /.our__clients -->\n";
echo "\n";
echo "      <section class=\"news\">\n";
echo "        <div class=\"container\">\n";
echo "          <h1 class=\"new__title\">Интересные статьи</h1>\n";
echo "          <div class=\"block__card__news\">\n";
echo "            <a href=\"./typography.html\"\n";
echo "              ><div class=\"card__news\">\n";
echo "                <div class=\"block__img__new\">\n";
echo "                  <img\n";
echo "                    src=\"./img/Rectangle28.png\"\n";
echo "                    alt=\"img\"\n";
echo "                    class=\"new__img\"\n";
echo "                  />\n";
echo "                </div>\n";
echo "                <div class=\"new__cont__card\">\n";
echo "                  <p class=\"title__new__cont\">\n";
echo "                    Горячая вода — секрет вечной<br />молодости\n";
echo "                  </p>\n";
echo "                  <p class=\"text__cont__new\">\n";
echo "                    Человеческий организм на 75 – 80% состоит из<br />воды. Она\n";
echo "                    продлевает жизнь и восстанавливает<br />здоровье.\n";
echo "                  </p>\n";
echo "                </div>\n";
echo "              </div></a\n";
echo "            >\n";
echo "            <div class=\"card__news\">\n";
echo "              <div class=\"block__img__new\">\n";
echo "                <img src=\"./img/Rectangle29.png\" alt=\"img\" class=\"new__img\" />\n";
echo "              </div>\n";
echo "              <div class=\"new__cont__card\">\n";
echo "                <p class=\"title__new__cont\">\n";
echo "                  Горячая вода — секрет вечной<br />молодости\n";
echo "                </p>\n";
echo "                <p class=\"text__cont__new\">\n";
echo "                  Человеческий организм на 75 – 80% состоит из<br />воды. Она\n";
echo "                  продлевает жизнь и восстанавливает<br />здоровье.\n";
echo "                </p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <div class=\"card__news\">\n";
echo "              <div class=\"block__img__new\">\n";
echo "                <img src=\"./img/Rectangle30.png\" alt=\"img\" class=\"new__img\" />\n";
echo "              </div>\n";
echo "              <div class=\"new__cont__card\">\n";
echo "                <p class=\"title__new__cont\">\n";
echo "                  Горячая вода — секрет вечной<br />молодости\n";
echo "                </p>\n";
echo "                <p class=\"text__cont__new\">\n";
echo "                  Человеческий организм на 75 – 80% состоит из<br />воды. Она\n";
echo "                  продлевает жизнь и восстанавливает<br />здоровье.\n";
echo "                </p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <div class=\"card__news\">\n";
echo "              <div class=\"block__img__new\">\n";
echo "                <img src=\"./img/Rectangle31.png\" alt=\"img\" class=\"new__img\" />\n";
echo "              </div>\n";
echo "              <div class=\"new__cont__card\">\n";
echo "                <p class=\"title__new__cont\">\n";
echo "                  Горячая вода — секрет вечной<br />молодости\n";
echo "                </p>\n";
echo "                <p class=\"text__cont__new\">\n";
echo "                  Человеческий организм на 75 – 80% состоит из<br />воды. Она\n";
echo "                  продлевает жизнь и восстанавливает<br />здоровье.\n";
echo "                </p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <div class=\"card__news\">\n";
echo "              <div class=\"block__img__new\">\n";
echo "                <img src=\"./img/Rectangle32.png\" alt=\"img\" class=\"new__img\" />\n";
echo "              </div>\n";
echo "              <div class=\"new__cont__card\">\n";
echo "                <p class=\"title__new__cont\">\n";
echo "                  Горячая вода — секрет вечной<br />молодости\n";
echo "                </p>\n";
echo "                <p class=\"text__cont__new\">\n";
echo "                  Человеческий организм на 75 – 80% состоит из<br />воды. Она\n";
echo "                  продлевает жизнь и восстанавливает<br />здоровье.\n";
echo "                </p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <div class=\"card__news\">\n";
echo "              <div class=\"block__img__new\">\n";
echo "                <img src=\"./img/Rectangle34.png\" alt=\"img\" class=\"new__img\" />\n";
echo "              </div>\n";
echo "              <div class=\"new__cont__card\">\n";
echo "                <p class=\"title__new__cont\">\n";
echo "                  Горячая вода — секрет вечной<br />молодости\n";
echo "                </p>\n";
echo "                <p class=\"text__cont__new\">\n";
echo "                  Человеческий организм на 75 – 80% состоит из<br />воды. Она\n";
echo "                  продлевает жизнь и восстанавливает<br />здоровье.\n";
echo "                </p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <!-- /.block__card__news -->\n";
echo "        </div>\n";
echo "        <!-- /.container -->\n";
echo "      </section>\n";
echo "      <!-- /.news -->\n";
echo "    </main>\n";
echo "\n";
echo "    <footer class=\"footer\">\n";
echo "      <div class=\"container\">\n";
echo "        <div class=\"block__social__info\">\n";
echo "          <div class=\"about__company\">\n";
echo "            <h4 class=\"about__title\">О компании</h4>\n";
echo "            <div class=\"links__social\">\n";
echo "              <div class=\"left__social\">\n";
echo "                <a href=\"#\" class=\"link_soc\">Каталог </a\n";
echo "                ><a href=\"#\" class=\"link_soc\">Акции </a\n";
echo "                ><a href=\"#\" class=\"link_soc\">Услуги</a>\n";
echo "              </div>\n";
echo "              <!-- /.left__social -->\n";
echo "              <div class=\"right__social\">\n";
echo "                <a href=\"#\" class=\"link_soc\">О нас </a\n";
echo "                ><a href=\"#\" class=\"link_soc\">Новости </a\n";
echo "                ><a href=\"#\" class=\"link_soc\">Контакты</a>\n";
echo "              </div>\n";
echo "              <!-- /.right__social -->\n";
echo "              <div class=\"free__social\">\n";
echo "                <a href=\"#\" class=\"link_soc\">Доставка и оплата </a\n";
echo "                ><a href=\"#\" class=\"link_soc\">Гарантии и возврат </a\n";
echo "                ><a href=\"#\" class=\"link_soc\">Вакансии</a>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <!-- /.links__social -->\n";
echo "          </div>\n";
echo "          <!-- /.about__company -->\n";
echo "          <div class=\"about__company\">\n";
echo "            <h4 class=\"about__title\">Наши услуги</h4>\n";
echo "            <div class=\"links__social\">\n";
echo "              <div class=\"left__social\">\n";
echo "                <a href=\"#\" class=\"link_soc\">Брендирование воды </a\n";
echo "                ><a href=\"#\" class=\"link_soc\">Контрактный розлив </a\n";
echo "                ><a href=\"#\" class=\"link_soc\">Вода на розлив </a\n";
echo "                ><a href=\"#\" class=\"link_soc\">Бренды</a>\n";
echo "              </div>\n";
echo "              <!-- /.left__social -->\n";
echo "              <div class=\"right__social\">\n";
echo "                <a href=\"#\" class=\"link_soc\">Изготовление пэт тары </a\n";
echo "                ><a href=\"#\" class=\"link_soc\">Напитки оптом </a\n";
echo "                ><a href=\"#\" class=\"link_soc\">Вода оптом</a>\n";
echo "              </div>\n";
echo "              <!-- /.right__social -->\n";
echo "            </div>\n";
echo "            <!-- /.links__social -->\n";
echo "          </div>\n";
echo "          <!-- /.about__company -->\n";
echo "        <div class=\"wrapp_block_med\">\n";
echo "          <div class=\"info__company\">\n";
echo "            <p class=\"text__company\">\n";
echo "              © 2016—2019,<br />ООО «Берегиня», официальный<br />сайт, лицензия\n";
echo "              Минкомсвязи<br />№ 144842 от 8 июня 2016 г.\n";
echo "            </p>\n";
echo "          </div>\n";
echo "          <!-- /.info__company -->\n";
echo "          <div class=\"wrapp_med_soc\">\n";
echo "            <div class=\"social__media\">\n";
echo "              <a href=\"#\" class=\"media\"></a> <a href=\"#\" class=\"media__face\"></a>\n";
echo "              <a href=\"#\" class=\"media__inst\"></a>\n";
echo "              <a href=\"#\" class=\"media__you\"></a>\n";
echo "              <a href=\"#\" class=\"media__ok\"></a>\n";
echo "            </div>\n";
echo "            <!-- /.social__media -->\n";
echo "          </div>\n";
echo "          <!-- /.wrapp_med_soc -->\n";
echo "        </div>\n";
echo "        </div>\n";
echo "        <!-- /.block__social__info -->\n";
echo "        <div class=\"sub__footer\">\n";
echo "          <div class=\"wrapp__sub\">\n";
echo "            <div class=\"logo__footer\">\n";
echo "              <img\n";
echo "                src=\"./img/icon/Logofooter.svg\"\n";
echo "                alt=\"img\"\n";
echo "                class=\"logo_foot\"\n";
echo "              />\n";
echo "            </div>\n";
echo "            <div class=\"input__block\">\n";
echo "              <input type=\"text\" class=\"input__footer\" />\n";
echo "            </div>\n";
echo "            <div class=\"sub__footer_adress\">\n";
echo "              <img\n";
echo "                src=\"./img/icon/Group3.svg\"\n";
echo "                alt=\"icon\"\n";
echo "                class=\"adress__footer\"\n";
echo "              />\n";
echo "              <p class=\"text__adress__footer\">\n";
echo "                Московская область,<br /><strong>Раменский р-н, пос.</strong\n";
echo "                ><br /><strong>санатория «Раменское»</strong>\n";
echo "              </p>\n";
echo "            </div>\n";
echo "            <div class=\"call__footer\">\n";
echo "              <img\n";
echo "                src=\"./img/icon/interface3.svg\"\n";
echo "                alt=\"img\"\n";
echo "                class=\"call__icon__footer\"\n";
echo "              />\n";
echo "              <p class=\"numb__call_footer sett__footer\">8 (903) 578-85-77</p>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <!-- /.sub__footer -->\n";
echo "      </div>\n";
echo "      <!-- /.container -->\n";
echo "    </footer>\n";
echo "  </body>\n";
echo "</html>\n";
?>
